apiVersion: monitoring.coreos.com/v1alpha1
kind: AlertmanagerConfig
metadata:
  name: main-rules-alert-config
  namespace: monitoring
spec:
  route: 
    receiver: 'email'
    repeatInterval: 30m
    routes: 
    - matchers: 
      - name: alertname
        value: HostHighCpuLoad
    - matchers: 
      - name: alertname
        value: KubernetesPodCrushLooping
  receivers:
  - name: 'email'
    emailConfigs:
    - to: 'aleksandra.lutsenko23@gmail.com'
      from: 'aleksandra.lutsenko23@gmail.com'
      smarthost: 'smtp.gmail.com:587'
      authUsername: 'aleksandra.lutsenko23@gmail.com'
      authIdentity: 'aleksandra.lutsenko23@gmail.com'
      authPassword:
        name: gmail-auth
        key: password
